import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Documento principal
    { type: "doc", id: "index" },

    // Usage
    {
      type: "category",
      label: "Usage",
      collapsed: true,
      link: {
        type: "doc", // <- aquí le dices que lea un markdown
        id: "usage/index", // <- el markdown que se abrirá al click
      },
      items: [{ type: "doc", id: "usage/start" }],
    },

    // Reference
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      link: {
        type: "doc", // <- aquí le dices que lea un markdown
        id: "reference/index", // <- el markdown que se abrirá al click
      },
      items: [
        // CLI subcategory
        {
          type: "category",
          label: "CLI",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "reference/cli" }],
        },

        // Config subcategory
        {
          type: "category",
          label: "Config",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "reference/config" }],
        },

        // Lua subcategory
        {
          type: "category",
          label: "Lua",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "reference/lua" }],
        },

        // Std library subcategory
        {
          type: "category",
          label: "Std",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "reference/std" }],
        },
      ],
    },
  ],
};

export default sidebars;
