name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "website/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Prepare website
        run: cp -r docs/ website/ || true

      - name: Install & Build
        run: |
          cd website
          bun install
          bun run build

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r website/build/* deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          enable_jekyll: false
